#server:
#  port: 9000
#
#spring:
#  application:
#    name: config-server
#  profiles:
#    active: git
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/DTY17/library-config-yml.git
##        native:
##          search-locations:
##            - classpath:/configuration
##            - classpath:/configuration/platform
##            - classpath:/configuration/service

server:
  port: 9000

spring:
  application:
    name: config-server
  profiles:
    active: git   # choose which profile to run

  cloud:
    config:
      server:
        git:
          uri: https://github.com/DTY17/library-config-server-yml.git
          default-label: main
          search-paths: configuration,platform,service

---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configuration
            - classpath:/configuration/platform
            - classpath:/configuration/service

---
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DTY17/library-config-server-yml.git
          default-label: main
          search-paths: configuration,platform,service
